export const BatchKeeperAbi = [
  {
    inputs: [{ internalType: 'contract IMultiInvoker', name: 'invoker_', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'version', type: 'uint256' }],
    name: 'InitializableAlreadyInitializedError',
    type: 'error',
  },
  { inputs: [], name: 'InitializableNotInitializingError', type: 'error' },
  { inputs: [], name: 'InitializableZeroVersionError', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'sender', type: 'address' }],
    name: 'OwnableNotOwnerError',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'sender', type: 'address' }],
    name: 'OwnableNotPendingOwnerError',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'version', type: 'uint256' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'OwnerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'newPendingOwner', type: 'address' }],
    name: 'PendingOwnerUpdated',
    type: 'event',
  },
  { stateMutability: 'payable', type: 'fallback' },
  {
    inputs: [],
    name: 'FAILURE',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MARKETR_MAGIC_VALUE_WITHDRAW_ALL_COLLATERAL',
    outputs: [{ internalType: 'Fixed6', name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NO_REASON',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'acceptOwner', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'contract IMarket[]', name: 'markets', type: 'address[]' }],
    name: 'marketWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IERC20', name: 'token', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'transferToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IMarket', name: 'market', type: 'address' },
      { internalType: 'address[]', name: 'accounts', type: 'address[]' },
      { internalType: 'uint256[]', name: 'nonces', type: 'uint256[]' },
      {
        components: [
          { internalType: 'enum IMultiInvoker.PerennialAction', name: 'action', type: 'uint8' },
          { internalType: 'bytes', name: 'args', type: 'bytes' },
        ],
        internalType: 'struct IMultiInvoker.Invocation[]',
        name: 'commitment',
        type: 'tuple[]',
      },
      { internalType: 'uint256', name: 'commitmentValue', type: 'uint256' },
    ],
    name: 'tryExecute',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'uint256', name: 'nonce', type: 'uint256' },
          { internalType: 'bool', name: 'canExec', type: 'bool' },
          { internalType: 'bytes', name: 'reason', type: 'bytes' },
        ],
        internalType: 'struct BatchKeeper.ExecRes[]',
        name: 'res',
        type: 'tuple[]',
      },
      { internalType: 'UFixed18', name: 'reward', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IMarket', name: 'market', type: 'address' },
      { internalType: 'address[]', name: 'accounts', type: 'address[]' },
      {
        components: [
          { internalType: 'enum IMultiInvoker.PerennialAction', name: 'action', type: 'uint8' },
          { internalType: 'bytes', name: 'args', type: 'bytes' },
        ],
        internalType: 'struct IMultiInvoker.Invocation[]',
        name: 'commitment',
        type: 'tuple[]',
      },
      { internalType: 'uint256', name: 'commitmentValue', type: 'uint256' },
    ],
    name: 'tryLiquidate',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'bool', name: 'canLiq', type: 'bool' },
          { internalType: 'bytes', name: 'reason', type: 'bytes' },
          { internalType: 'UFixed6', name: 'reward', type: 'uint256' },
        ],
        internalType: 'struct BatchKeeper.LiqRes[]',
        name: 'res',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newPendingOwner', type: 'address' }],
    name: 'updatePendingOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
] as const
